-- phpMyAdmin SQL Dump
-- version 4.4.15.10
-- https://www.phpmyadmin.net
--
-- Хост: localhost
-- Час створення: Трв 25 2026 р., 10:29
-- Версія сервера: 5.5.64-MariaDB
-- Версія PHP: 7.3.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База даних: `lavoks`
--

--
-- Дамп даних таблиці `products`
--

INSERT INTO `products` (`id`, `slug`, `name`, `category_id`, `description`, `active`, `created_at`, `image`, `imagewebp`, `imageswebp`, `price`, `code`, `lazer_type_id`, `meta_title`, `meta_keyword`, `meta_description`, `gender_type_id`, `colors`, `popular`, `new`, `to_order`, `is_absent`, `photo_updated_at`, `seo_title`, `seo_content`, `new_leather_color`, `new_leather_type`, `new_model`, `gtin`, `mpn`, `updated_at`, `order`, `size`, `hasThumbnail`, `imageOld`, `jpgDeleted`, `photosMoved`, `mainImage`, `reviewCount`, `rating`, `img_titles`, `reserv_price`) VALUES
(3784, 'kosserd-tzhzh-g-2', 'Косметичка "Серце"', 162, '<p><strong>Косметичка "Серце"</strong><br>• Розмір: діаметр 11 см., висота 3,5см.<br>• Колір виробу: жовтий манго<br>• Вид шкіри: натуральна шкіра кайзер<br>• Вид поверхні: гарний, насичений колір, глянцева поверхня<br>• Колір фурнітури : нікель (білий)<br>• Всередині одне велике відділення<br>• Є можливість зробити індивидуальне <a href="https://lavoks.com/tisnennya">тиснення</a> – ім`я, або ініціали, або пам`ятну дату, чи інші види <a href="https://lavoks.com/tisnennya">тиснення</a> (можна подивитись приклади в розділі "<a href="https://lavoks.com/tisnennya">тиснення</a>")</p>', 1, '2026-05-12 03:56:45', '["products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-60919.webp","products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-2427.webp","products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-43899.webp"]', '["products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-60919.webp","products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-2427.webp","products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-43899.webp"]', '["products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-60919.webp","products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-2427.webp","products\\/3784\\/kosmetichki-serce-kosserd-tzzg-2-43899.webp"]', 720, 'КосСерд-ТЖЖ+Г-2', 4, '', '', '', ',1,', ',75,', 1, 0, 0, 0, NULL, '', '', 0, 0, 0, '37848012865187', 'LA37848012865187VOKS', '2026-05-12 04:00:16', 1, 'діаметр 11 см., висота 3,5см.', NULL, NULL, NULL, NULL, 'products/3784/kosmetichki-serce-kosserd-tzzg-2-60919.webp', NULL, NULL, NULL, 0),
(2498, 'kosserd-mm', 'Косметичка "Сердце"', 162, '<p><strong>Косметичка "Серце"</strong><br />&bull; Розмір: діаметр 11 см., висота 3,5см.<br />&bull; Колір виробу: марсала<br />&bull; Вид шкіри: натуральна шкіра крейзі хорс&nbsp;<br />&bull; Вид поверхні: матова поверхня з вінтажним ефектом, глибокий насичений колір<br />&bull; Колір фурнітури : антік (жовтий)<br />&bull; Всередині одне велике відділення<br />&bull; Є можливість зробити індивидуальне <a href="https://lavoks.com/tisnennya">тиснення</a> &ndash; ім`я, або ініціали, або пам`ятну дату, чи інші види <a href="https://lavoks.com/tisnennya">тиснення</a> (можна подивитись приклади в розділі "<a href="https://lavoks.com/tisnennya">тиснення</a>")</p>', 1, '2022-10-21 04:16:29', '["products\\/2498\\/kosmetichki-serce_kosserd-mm-12.webp","products\\/2498\\/kosmetichki-serce_kosserd-mm-14.webp","products\\/2498\\/kosmetichki-serce_kosserd-mm-15.webp","products\\/2498\\/kosmetichki-serce_kosserd-mm-13.webp"]', '["products\\/October2022\\/j9TMvoRncrRs1KR2beci.webp","products\\/October2022\\/O8Lngx3lIBhfOayxkYkT.webp","products\\/October2022\\/UR4bFndiSb3v3rbEdUBQ.webp","products\\/October2022\\/P6RqgBqwMsvMGYdaAmiA.webp"]', '["products\\/2498\\/kosmetichki-serce_kosserd-mm-12.webp","products\\/2498\\/kosmetichki-serce_kosserd-mm-14.webp","products\\/2498\\/kosmetichki-serce_kosserd-mm-15.webp","products\\/2498\\/kosmetichki-serce_kosserd-mm-13.webp"]', 720, 'КосСерд-ММ', 8, '', '', '', ',1,', ',11,', 0, NULL, 0, 0, NULL, '', '', 0, 0, 0, '24985819714428', 'LA24985819714428VOKS', '2025-12-02 12:14:06', 2, 'діаметр 11 см., висота 3,5см.', NULL, '["products\\/October2022\\/j9TMvoRncrRs1KR2beci.JPG","products\\/October2022\\/O8Lngx3lIBhfOayxkYkT.JPG","products\\/October2022\\/UR4bFndiSb3v3rbEdUBQ.JPG","products\\/October2022\\/P6RqgBqwMsvMGYdaAmiA.JPG"]', 1, 1, 'products/October2022/j9TMvoRncrRs1KR2beci-cropped.webp', NULL, NULL, NULL, 720),
(2470, 'kosserd-zz-kaj', 'Косметичка "Сердце"', 162, '<p><strong>&nbsp;Косметичка "Серце"</strong><br />&bull; Розмір: діаметр 11 см., висота 3,5см.<br />&bull; Колір виробу: зелений<br />&bull; Вид шкіри: натуральна шкіра крейзі хорс з <a href="https://lavoks.com/tisnennya">тисненням</a> "під каймана"<br />&bull; Вид поверхні: матова поверхня з вінтажним ефектом, глибокий насичений колір<br />&bull; Колір фурнітури : антік (жовтий)<br />&bull; Всередині одне велике відділення<br />&bull; Є можливість зробити індивидуальне <a href="https://lavoks.com/tisnennya">тиснення</a> &ndash; ім`я, або ініціали, або пам`ятну дату, чи інші види <a href="https://lavoks.com/tisnennya">тиснення</a> (можна подивитись приклади в розділі "<a href="https://lavoks.com/tisnennya">тиснення</a>")</p>', 1, '2022-10-05 02:03:42', '["products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-5.webp","products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-9.webp","products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-10.webp","products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-6.webp"]', '["products\\/October2022\\/F8FBPugju7xuhwMLueTc.webp","products\\/October2022\\/oi6AbvB961E7gEoW5z25.webp","products\\/October2022\\/z2xVwZuttXvVKVzfbBOH.webp","products\\/October2022\\/o6yVrPv0Zfyfdk7XKgZH.webp"]', '["products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-5.webp","products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-9.webp","products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-10.webp","products\\/2470\\/kosmetichki-serce_kosserd-zz-kaj-6.webp"]', 720, 'КосСерд-ЗЗ-Кай', 32, '', '', '', ',1,', ',10,', 0, NULL, 0, 0, NULL, '', '', 0, 0, 0, '24705720297771', 'LA24705720297771VOKS', '2025-12-02 12:14:06', 3, 'діаметр 11 см., висота 3,5см.', NULL, '["products\\/October2022\\/F8FBPugju7xuhwMLueTc.JPG","products\\/October2022\\/oi6AbvB961E7gEoW5z25.JPG","products\\/October2022\\/z2xVwZuttXvVKVzfbBOH.JPG","products\\/October2022\\/o6yVrPv0Zfyfdk7XKgZH.JPG"]', 1, 1, 'products/October2022/F8FBPugju7xuhwMLueTc-cropped.webp', NULL, NULL, NULL, 720),
(2262, 'kosserd-kr-2', 'Косметичка "Серце"', 162, '<p><strong>Косметичка "Серце"</strong><br />&bull; Розмір: діаметр 11 см., висота 3,5см.<br />&bull; Колір виробу: червоний<br />&bull; Вид шкіри: натуральна шкіра кайзер<br />&bull; Вид поверхні: гарний, насичений колір, глянцева поверхня<br />&bull; Колір фурнітури : нікель (білий)<br />&bull; Всередині одне велике відділення<br />&bull; Є можливість зробити індивидуальне <a href="https://lavoks.com/tisnennya">тиснення</a> &ndash; ім`я, або ініціали, або пам`ятну дату, чи інші види <a href="https://lavoks.com/tisnennya">тиснення</a> (можна подивитись приклади в розділі "<a href="https://lavoks.com/tisnennya">тиснення</a>")</p>', 1, '2022-02-03 04:07:10', '["products\\/2262\\/kosmetichki-serce_kosserd-kr-2-14.webp","products\\/2262\\/kosmetichki-serce_kosserd-kr-2-11.webp","products\\/2262\\/kosmetichki-serce_kosserd-kr-2-9.webp"]', '["products\\/February2022\\/QsaHYeKUCPOLHS2JOVrx.webp","products\\/February2022\\/WXEBHt4dVz26k5oIsDqr.webp","products\\/February2022\\/WcJ4hLX9jBXduZULxNJx.webp"]', '["products\\/2262\\/kosmetichki-serce_kosserd-kr-2-14.webp","products\\/2262\\/kosmetichki-serce_kosserd-kr-2-11.webp","products\\/2262\\/kosmetichki-serce_kosserd-kr-2-9.webp"]', 720, 'КосСерд-Кр-2', 4, '', '', '', ',1,', ',8,', 1, NULL, 0, 0, NULL, '', '', 0, 0, 0, '22625738472046', 'LA22625738472046VOKS', '2025-12-02 12:14:05', 4, 'діаметр 11 см., висота 3,5см.', NULL, '["products\\/February2022\\/QsaHYeKUCPOLHS2JOVrx.JPG","products\\/February2022\\/WXEBHt4dVz26k5oIsDqr.JPG","products\\/February2022\\/WcJ4hLX9jBXduZULxNJx.JPG"]', 1, 1, 'products/February2022/QsaHYeKUCPOLHS2JOVrx-cropped.webp', NULL, NULL, NULL, 720),
(2261, 'kosserd-a-kr-2', 'Косметичка "Серце"', 162, '<p><span class="description"><strong>&nbsp;Косметичка "Серце"</strong><br />&bull; Розмір: діаметр 11 см., висота 3,5см.<br />&bull; Колір виробу: червоний<br />&bull; Вид шкіри: натуральна шкіра кайзер<br />&bull; Вид поверхні: гарний, насичений колір, глянцева поверхня<br />&bull; Колір фурнітури : антік (жовтий)<br />&bull; Всередині одне велике відділення<br />&bull; Є можливість зробити індивидуальне <a href="https://lavoks.com/tisnennya">тиснення</a> &ndash; ім`я, або ініціали, або пам`ятну дату, чи інші види <a href="https://lavoks.com/tisnennya">тиснення</a> (можна подивитись приклади в розділі "<a href="https://lavoks.com/tisnennya">тиснення</a>")</span></p>', 1, '2022-02-03 04:02:58', '["products\\/2261\\/kosmetichki-serce_kosserd-a-kr-2-14.webp","products\\/2261\\/kosmetichki-serce_kosserd-a-kr-2-14.webp","products\\/2261\\/kosmetichki-serce_kosserd-a-kr-2-5.webp"]', '["products\\/February2022\\/5BakDvUiuRfUSb85Zolb.webp","products\\/February2022\\/IFuHM17qLCtq0iHdEE3C.webp","products\\/February2022\\/3YqIIAIBeDXnNnqymjFM.webp"]', '["products\\/2261\\/kosmetichki-serce_kosserd-a-kr-2-14.webp","products\\/2261\\/kosmetichki-serce_kosserd-a-kr-2-14.webp","products\\/2261\\/kosmetichki-serce_kosserd-a-kr-2-5.webp"]', 720, 'КосСерд(а)-Кр-2', 4, '', '', '', ',1,', ',8,', 1, NULL, 0, 0, NULL, '', '', 0, 0, 0, '22613590570074', 'LA22613590570074VOKS', '2025-12-02 12:14:05', 5, 'діаметр 11 см., висота 3,5см.', NULL, '["products\\/February2022\\/5BakDvUiuRfUSb85Zolb.JPG","products\\/February2022\\/IFuHM17qLCtq0iHdEE3C.JPG","products\\/February2022\\/3YqIIAIBeDXnNnqymjFM.JPG"]', 1, 1, 'products/February2022/5BakDvUiuRfUSb85Zolb-cropped.webp', NULL, NULL, NULL, 720);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
